# Generated by Django 4.2 on 2023-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('prev_loc', models.CharField(max_length=100)),
                ('thumb_loc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
